load("@aspect_bazel_lib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//awk:__subpackages__"])

exports_files(["awk.bzl"])

bzl_library(
    name = "awk",
    srcs = ["awk.bzl"],
)
