on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Export BCR presubmit config
        id: config
        run: |
          echo 'presubmit<<__BCR_CONFIG__' >> "$GITHUB_OUTPUT"
          yq -o=json '.' .bcr/presubmit.yml >> "$GITHUB_OUTPUT"
          echo '__BCR_CONFIG__' >> "$GITHUB_OUTPUT"
  bcr-presubmit:
    name: 🌿
    runs-on: ${{ matrix.platform }}
    needs: translate
    strategy:
      matrix:
        platform: ["ubuntu-22.04", "macos-latest"]
        bazel: ["9.*", "8.x", "7.x"] # , "6.x"]
        module_path: ${{ needs.translate.outputs.config }} # ["examples"]
        test_targets: ["//..."]
    steps:
      - uses: actions/checkout@v5
      - run: bazel test ${{ matrix.test_targets }}
        working-directory: ${{ matrix.module_path }}
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
